methods: {
    'DPBGMM': {
            weight_concentration_prior_type: "dirichlet_process",
            weight_concentration_prior: 0.1,
            covariance_type: "full",
            n_init: 10,
            max_iter: 1000,
            random_state: 42,
    },
    'KMeans': {
            init: "k-means++",
            n_init: 10,
            max_iter: 1000,
            random_state: 42,
    },
}